#!/usr/bin/env python3
"""
gen_widerface_test_image.py
============================
Converts a WiderFace val image into a C header file for WIDERFACE_TEST mode.

Run from ai8x-training/:
    python gen_widerface_test_image.py \
        --data "C:/Users/36306/STM32CubeIDE/.../retinaface" \
        --idx 6 \
        --out ../ai8x-synthesis/synthed_net/fcosface88/widerface_test_image.h

The output header defines:
    WIDERFACE_TEST_INPUT[]  - 7744 uint32 words (88x88 pixels, 0x00BBGGRR unsigned)
    WIDERFACE_TEST_GT[]     - ground truth boxes as {x1,y1,x2,y2} int pairs
    WIDERFACE_TEST_N_GT     - number of GT boxes
    WIDERFACE_TEST_IDX      - dataset index used

Pixel format matches what the camera firmware produces:
    unsigned uint8 R,G,B packed as 0x00BBGGRR (no XOR 0x80)
    Same as sampledata.h format.
"""

import argparse
import os
import sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--data',  required=True, help='Retinaface data root')
    p.add_argument('--idx',   type=int, default=6, help='Val image index')
    p.add_argument('--out',   required=True, help='Output .h file path')
    p.add_argument('--show',  action='store_true', help='Show image preview')
    args = p.parse_args()

    from datasets.widerface88 import WiderFace88
    ds = WiderFace88(args.data, split='val', augment=False)
    print(f'Dataset: {len(ds)} val images')

    img_tensor, target = ds[args.idx]
    gt_boxes = target['boxes']  # (N,4) xyxy float32 in 88x88 space

    print(f'Image idx={args.idx}: {len(gt_boxes)} GT boxes')
    for i, b in enumerate(gt_boxes):
        print(f'  GT[{i}]: x1={b[0]:.1f} y1={b[1]:.1f} x2={b[2]:.1f} y2={b[3]:.1f}')

    # Convert tensor [-1,1] CHW -> unsigned [0,255] HWC
    # img_tensor is float32 CHW [-1,1]
    # Normalize back: pixel = (img_tensor + 1) * 127.5
    arr = img_tensor.permute(1, 2, 0).numpy()  # HWC float32 [-1,1]
    arr_u8 = ((arr + 1.0) * 127.5).clip(0, 255).astype(np.uint8)  # HWC uint8 [0,255]

    if args.show:
        Image.fromarray(arr_u8, 'RGB').show()

    # Pack as 0x00BBGGRR uint32 per pixel (HWC order, row by row)
    # This matches sampledata.h format and what camera firmware produces
    H, W, _ = arr_u8.shape
    assert H == 88 and W == 88, f"Expected 88x88, got {H}x{W}"

    words = []
    for row in range(H):
        for col in range(W):
            r = int(arr_u8[row, col, 0])
            g = int(arr_u8[row, col, 1])
            b = int(arr_u8[row, col, 2])
            word = (b << 16) | (g << 8) | r
            words.append(word)

    assert len(words) == 7744

    # Write header
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, 'w') as f:
        f.write('/* widerface_test_image.h\n')
        f.write(f' * WiderFace val image idx={args.idx}, {len(gt_boxes)} GT boxes\n')
        f.write(' * Generated by gen_widerface_test_image.py\n')
        f.write(' * Format: 0x00BBGGRR unsigned uint8 per channel, HWC 88x88\n')
        f.write(' */\n\n')
        f.write('#pragma once\n\n')
        f.write(f'#define WIDERFACE_TEST_IDX   {args.idx}\n')
        f.write(f'#define WIDERFACE_TEST_N_GT  {len(gt_boxes)}\n\n')

        # GT boxes as integer array
        f.write('/* GT boxes: {x1, y1, x2, y2} in 88x88 pixel coords */\n')
        f.write('static const int widerface_test_gt[][4] = {\n')
        for b in gt_boxes:
            x1, y1, x2, y2 = int(b[0]), int(b[1]), int(b[2]), int(b[3])
            f.write(f'    {{{x1}, {y1}, {x2}, {y2}}},\n')
        f.write('};\n\n')

        # Pixel data
        f.write('/* Input pixels: 7744 words, one uint32 per pixel, 0x00BBGGRR */\n')
        f.write('#define WIDERFACE_TEST_INPUT { \\\n')
        for i, w in enumerate(words):
            if i % 8 == 0:
                f.write('  ')
            f.write(f'0x{w:06x}')
            if i < len(words) - 1:
                f.write(', ')
            if (i + 1) % 8 == 0:
                f.write(' \\\n')
        f.write('}\n')

    print(f'\nWrote: {args.out}')
    print(f'  {len(words)} pixel words')
    print(f'  {len(gt_boxes)} GT boxes')
    print('\nNow add to your project and compile with #define WIDERFACE_TEST')


if __name__ == '__main__':
    main()
