#!/usr/bin/env python3
"""
make_sample_input.py
====================
Converts a face image into a C header file that can be compiled
directly into the MAX78000 firmware for static inference testing.

Usage:
    python make_sample_input.py face.jpg

Output:
    sample_face.h   -- include this in main.c instead of feeding camera data

The output format matches what your model expects:
  - Resized to 224x224
  - RGB888, one uint32_t per pixel
  - Format: 0x00BBGGRR with each channel XOR'd with 0x80
    i.e.  value = ((b ^ 0x80) << 16) | ((g ^ 0x80) << 8) | (r ^ 0x80)
  - 224*224 = 50176 uint32_t values
"""

import sys
import numpy as np
from PIL import Image

def convert_image(path):
    # Load and resize
    img = Image.open(path).convert("RGB")
    img = img.resize((224, 224), Image.BILINEAR)
    arr = np.array(img, dtype=np.uint8)  # shape (224, 224, 3)

    # Build uint32 array in 0x00BBGGRR ^ 0x00808080 format
    r = arr[:, :, 0].astype(np.uint32)
    g = arr[:, :, 1].astype(np.uint32)
    b = arr[:, :, 2].astype(np.uint32)

    pixels = (((b ^ 0x80) << 16) | ((g ^ 0x80) << 8) | (r ^ 0x80)).flatten()

    # Write C header
    out_path = "sample_face.h"
    with open(out_path, "w") as f:
        f.write("// Auto-generated by make_sample_input.py\n")
        f.write("// Static face input for MAX78000 FcosFace firmware test\n")
        f.write("// Format: 0x00BBGGRR with each channel ^ 0x80\n\n")
        f.write("#ifndef __SAMPLE_FACE_H__\n")
        f.write("#define __SAMPLE_FACE_H__\n\n")
        f.write(f"#define SAMPLE_FACE_W 224\n")
        f.write(f"#define SAMPLE_FACE_H 224\n")
        f.write(f"#define SAMPLE_FACE_COUNT {len(pixels)}\n\n")
        f.write("static const uint32_t sample_face_data[] = {\n")

        for i, val in enumerate(pixels):
            if i % 8 == 0:
                f.write("    ")
            f.write(f"0x{val:08X}")
            if i < len(pixels) - 1:
                f.write(", ")
            if (i + 1) % 8 == 0:
                f.write("\n")

        f.write("\n};\n\n")
        f.write("#endif // __SAMPLE_FACE_H__\n")

    print(f"Written {len(pixels)} pixels to {out_path}")
    print(f"Array size: {len(pixels) * 4 / 1024:.1f} KB")
    print(f"First pixel (r,g,b): ({arr[0,0,0]}, {arr[0,0,1]}, {arr[0,0,2]})")
    print(f"First encoded value: 0x{pixels[0]:08X}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python make_sample_input.py <face_image.jpg>")
        sys.exit(1)
    convert_image(sys.argv[1])
