/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// fcosface88
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix fcosface88 --checkpoint-file trained/fcosface88-q.pth --config-file networks/fcosface88.yaml --sample-input tests/sample_widerface.npy --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 8 layers
// Input data: HWC
// Layer 0: 3x88x88, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x44x44 output
// Layer 1: 16x44x44, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x44x44 output
// Layer 2: 32x44x44, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x22x22 output
// Layer 3: 32x22x22, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x22x22 output
// Layer 4: 64x22x22, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x22x22 output
// Layer 5: 64x22x22, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x22x22 output
// Layer 6: 64x22x22, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x22x22 output
// Layer 7: 32x22x22, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, no activation, 5x22x22 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0}

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 96);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 80);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 69);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 64);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000007; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x00010059; // Rows
  *((volatile uint32_t *) 0x50100090) = 0x00010059; // Columns
  *((volatile uint32_t *) 0x50100190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00002ba0; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x05000578; // Mask offset and count
  *((volatile uint32_t *) 0x50100690) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50100790) = 0x00006000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0x00070007; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x00010059; // Rows
  *((volatile uint32_t *) 0x50500090) = 0x00010059; // Columns
  *((volatile uint32_t *) 0x50500190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x05000578; // Mask offset and count
  *((volatile uint32_t *) 0x50500690) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50500790) = 0x00007040; // Post processing register

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x00010059; // Rows
  *((volatile uint32_t *) 0x50900090) = 0x00010059; // Columns
  *((volatile uint32_t *) 0x50900190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x05000578; // Mask offset and count
  *((volatile uint32_t *) 0x50900690) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50900790) = 0x00006000; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x00010059; // Rows
  *((volatile uint32_t *) 0x50d00090) = 0x00010059; // Columns
  *((volatile uint32_t *) 0x50d00190) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00210) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00290) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00310) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x05000578; // Mask offset and count
  *((volatile uint32_t *) 0x50d00690) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00790) = 0x00006000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50100094) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x0000ab20; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x050005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100694) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50100794) = 0x00002000; // Post processing register

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50500094) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x050005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500694) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50500794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50900094) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x050005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900694) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50900794) = 0x00002000; // Post processing register

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50d00094) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x050005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00694) = 0x0000002b; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00794) = 0x00003000; // Post processing register

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50100098) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50100198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100598) = 0x0000aba0; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x060006f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100698) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50100798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50500098) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50500198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x060006f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500698) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50500798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50900098) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50900198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x060006f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900698) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50900798) = 0x00002000; // Post processing register

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0001002d; // Rows
  *((volatile uint32_t *) 0x50d00098) = 0x0001002d; // Columns
  *((volatile uint32_t *) 0x50d00198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00218) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00598) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x060006f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00698) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00798) = 0x00003020; // Post processing register

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x5010009c) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5010059c) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x070008f8; // Mask offset and count
  *((volatile uint32_t *) 0x5010069c) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x5010079c) = 0x00005000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x5050009c) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x070008f8; // Mask offset and count
  *((volatile uint32_t *) 0x5050069c) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x5050079c) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x5090009c) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x070008f8; // Mask offset and count
  *((volatile uint32_t *) 0x5090069c) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x5090079c) = 0x00004000; // Post processing register

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x50d0009c) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x070008f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0069c) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50d0079c) = 0x00004000; // Post processing register

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50100320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a0) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a0) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50500320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a0) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a0) = 0x00005000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50900320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a0) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a0) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50900720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50d00320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a0) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a0) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50d00720) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a4) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a4) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a4) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a4) = 0x00005000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x020003f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a4) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x501000a8) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50100328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x040004f8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a8) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a8) = 0x00005040; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x505000a8) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50500328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x040004f8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a8) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a8) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x509000a8) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50900328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x040004f8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a8) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a8) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00010017; // Rows
  *((volatile uint32_t *) 0x50d000a8) = 0x00010017; // Columns
  *((volatile uint32_t *) 0x50d00328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x040004f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a8) = 0x00000015; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a8) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00000015; // Rows
  *((volatile uint32_t *) 0x501000ac) = 0x00000015; // Columns
  *((volatile uint32_t *) 0x5010032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x00016920; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x51005120; // Mask offset and count
  *((volatile uint32_t *) 0x5010012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x00006000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00000015; // Rows
  *((volatile uint32_t *) 0x505000ac) = 0x00000015; // Columns
  *((volatile uint32_t *) 0x5050032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x51005120; // Mask offset and count
  *((volatile uint32_t *) 0x5050012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007ac) = 0x00006000; // Post processing register
  *((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00000015; // Rows
  *((volatile uint32_t *) 0x509000ac) = 0x00000015; // Columns
  *((volatile uint32_t *) 0x5090032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x51005120; // Mask offset and count
  *((volatile uint32_t *) 0x5090012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007ac) = 0x00007040; // Post processing register

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00000015; // Rows
  *((volatile uint32_t *) 0x50d000ac) = 0x00000015; // Columns
  *((volatile uint32_t *) 0x50d0032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x00002000; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x51005120; // Mask offset and count
  *((volatile uint32_t *) 0x50d0012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007ac) = 0x00006000; // Post processing register


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;
  int i;

  // Custom unload for this network, layer 7: 32-bit data, shape: (5, 22, 22)
  addr = (volatile uint32_t *) 0x50404000;
  for (i = 0; i < 242; i++) {
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
    *out_buf++ = *addr++;
  }
  addr = (volatile uint32_t *) 0x5040c000;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c010;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c020;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c030;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c040;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c050;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c060;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c070;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c080;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c090;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c0f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c100;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c110;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c120;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c130;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c140;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c150;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c160;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c170;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c180;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c190;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c1f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c200;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c210;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c220;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c230;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c240;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c250;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c260;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c270;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c280;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c290;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c2f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c300;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c310;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c320;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c330;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c340;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c350;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c360;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c370;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c380;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c390;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c3f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c400;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c410;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c420;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c430;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c440;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c450;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c460;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c470;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c480;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c490;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c4f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c500;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c510;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c520;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c530;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c540;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c550;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c560;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c570;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c580;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c590;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c5f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c600;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c610;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c620;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c630;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c640;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c650;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c660;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c670;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c680;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c690;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c6f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c700;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c710;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c720;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c730;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c740;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c750;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c760;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c770;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c780;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c790;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c7f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c800;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c810;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c820;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c830;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c840;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c850;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c860;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c870;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c880;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c890;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c8f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c900;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c910;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c920;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c930;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c940;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c950;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c960;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c970;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c980;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c990;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040c9f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ca90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040caa0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cab0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cac0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cad0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cae0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040caf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cb90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cba0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cbb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cbc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cbd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cbe0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cbf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cc90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cca0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ccb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ccc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ccd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cce0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ccf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cd90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cda0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cdb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cdc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cdd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cde0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cdf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ce90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cea0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ceb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cec0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ced0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cee0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cef0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cf90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cfa0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cfb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cfc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cfd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cfe0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040cff0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d000;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d010;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d020;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d030;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d040;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d050;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d060;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d070;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d080;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d090;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d0f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d100;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d110;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d120;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d130;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d140;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d150;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d160;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d170;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d180;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d190;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d1f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d200;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d210;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d220;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d230;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d240;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d250;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d260;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d270;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d280;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d290;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d2f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d300;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d310;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d320;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d330;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d340;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d350;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d360;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d370;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d380;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d390;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d3f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d400;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d410;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d420;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d430;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d440;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d450;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d460;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d470;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d480;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d490;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d4f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d500;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d510;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d520;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d530;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d540;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d550;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d560;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d570;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d580;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d590;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d5f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d600;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d610;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d620;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d630;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d640;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d650;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d660;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d670;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d680;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d690;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d6f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d700;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d710;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d720;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d730;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d740;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d750;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d760;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d770;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d780;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d790;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d7f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d800;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d810;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d820;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d830;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d840;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d850;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d860;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d870;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d880;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d890;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d8f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d900;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d910;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d920;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d930;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d940;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d950;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d960;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d970;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d980;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d990;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9a0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9b0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9c0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9d0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9e0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040d9f0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040da90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040daa0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dab0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dac0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dad0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dae0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040daf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040db90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dba0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dbb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dbc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dbd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dbe0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dbf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dc90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dca0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dcb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dcc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dcd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dce0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dcf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd30;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd40;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd50;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd60;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd70;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd80;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dd90;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dda0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ddb0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ddc0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ddd0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040dde0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040ddf0;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040de00;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040de10;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040de20;
  *out_buf++ = *addr++;
  addr += 0x0003;
  addr = (volatile uint32_t *) 0x5040de30;
  *out_buf++ = *addr++;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

